name: Code Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Actualizado a v3 para Node.js 20

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Actualizado a v2 para Node.js 20
      with:
        driver: docker-container
        buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
        install: false
        use: true

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and run Docker image
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        docker build -t asistente-ia-revision .
        docker run --rm --env-file .env asistente-ia-revision

    - name: Complete job
      run: echo "Job completed"
